name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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N }}
          GIST_ID: ${{ https://gist.github.com/woong12/ }}
          TIMEZONE: Asia/Seoul
